// src/components/app/Footer.vue
<template>
    <footer class="footer">
        <div class="links">
            <a href="https://github.com/KubaJastrz/find-types" class="link" title="Source code">
                <GithubIcon />
            </a>
        </div>
        <span class="powered-by">
            Powered by <a href="https://npms.io/" class="link">npms.io</a> and
            <a href="https://unpkg.com/" class="link">unpkg</a>
        </span>
    </footer>
</template>

<script lang="ts">
import Vue from 'vue';
import GithubIcon from '@/assets/icons/github.svg';

export default Vue.extend({
    components: {
        GithubIcon,
    },
});
</script>

<style lang="scss" scoped>
@import 'helpers';

.footer {
    display: flex;
    flex-direction: column;
    align-items: center;
    font-size: 0.85em;
    color: #666;
    padding: 8px;
    transition: 100ms ease-in-out;

    @include respond-from(mobile-large) {
        font-size: 0.9em;
    }

    &:hover {
        color: #333;
    }
}

.links {
    margin-bottom: 8px;

    .link {
        @extend %link-unstyled;
    }
}

.powered-by .link {
    @extend %link-default;
}
</style>

// src/components/Footer.tsx
import React from 'react';
import styled from 'styled-components';

import { Link, CleanLink } from '@/components/Framework';
import { ReactComponent as GithubIcon } from '@/assets/icons/github.svg';
import { MEDIA } from '@/styles/helpers';

interface Props {
  className?: string;
}

function Footer({ className }: Props) {
  return (
    <StyledFooter className={className}>
      <Links>
        <CleanLink href="https://github.com/KubaJastrz/find-types" title="Source code">
          <GithubIcon />
        </CleanLink>
      </Links>
      <p>
        Powered by <Link href="https://www.npmjs.com/">npm</Link> and{' '}
        <Link href="https://unpkg.com/">unpkg</Link>
      </p>
    </StyledFooter>
  );
}

const StyledFooter = styled.footer`
  display: flex;
  flex-direction: column;
  align-items: center;
  font-size: 0.85em;
  color: #666;
  padding: 8px;
  transition: 100ms ease-in-out;

  ${MEDIA.sm} {
    font-size: 0.9em;
  }

  &:hover {
    color: #333;
  }
`;

const Links = styled.div`
  margin-bottom: 8px;
`;

export default Footer;
