// src/components/Autosuggest/Autosuggest.tsx
import React from 'react';

import * as Styled from './Autosuggest.styles';
import SuggestionBox from './SuggestionBox';
import { Suggestion } from '@/types';

export interface Props {
  initialValue: string;
  items: Suggestion[];
  placeholder?: string;
  autoFocus?: boolean;
  onChange: (textInput: string) => void;
  onSelect: (textInput: string) => void;
  getValueFromItem: (item: Suggestion) => string;
}

interface State {
  inputText: string;
  isOpen: boolean;
  isFocused: boolean;
  highlightedIndex?: number;
  itemsKey: string;
  canSuggestionsBeShown: boolean;
}

class Autosuggest extends React.Component<Props, State> {
  state: Readonly<State> = {
    inputText: this.props.initialValue,
    isOpen: false,
    isFocused: false,
    highlightedIndex: undefined,
    itemsKey: '',
    canSuggestionsBeShown: true,
  };

  private inputRef = React.createRef<HTMLInputElement>();

  private ignoreBlur = false;

  canBeOpened = () => {
    const { inputText, itemsKey, canSuggestionsBeShown } = this.state;

    return canSuggestionsBeShown && inputText.toLowerCase().startsWith(itemsKey);
  };

  maybeOpen = () => {
    if (this.state.isOpen) {
      return;
    }

    this.setState(state => ({ isOpen: state.isFocused && this.canBeOpened() }));
  };

  close = () => {
    this.setState({
      isOpen: false,
      highlightedIndex: undefined,
    });
  };

  handleSelect(item: Suggestion) {
    const value = this.props.getValueFromItem(item);
    this.props.onSelect(value);
    this.close();
    this.setState({
      inputText: value,
      itemsKey: value,
      canSuggestionsBeShown: false,
    });
  }

  handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { value } = event.target;
    this.setState({
      inputText: value,
      canSuggestionsBeShown: true,
    });
    this.props.onChange(value);
    this.maybeOpen();
    if (value.length === 0) {
      this.close();
    }
  };

  handleFocus = () => {
    this.setState({ isFocused: true });
    this.maybeOpen();
  };

  handleBlur = () => {
    if (this.ignoreBlur && this.inputRef.current) {
      this.inputRef.current.focus();
      return;
    }
    this.setState({ isFocused: false });
    this.close();
  };

  handleKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    const { key } = event;
    const { isOpen, highlightedIndex } = this.state;

    if (key === 'Enter') {
      this.ignoreBlur = false;
      if (!isOpen) {
        return;
      } else if (highlightedIndex === undefined) {
        this.setState({ isOpen: false });
      } else {
        event.preventDefault();
        this.selectHighlightedItem();
      }
    } else if (key === 'Tab') {
      this.ignoreBlur = false;
      if (highlightedIndex !== undefined) {
        const item = this.getItemByIndex(highlightedIndex);
        const value = this.props.getValueFromItem(item);
        if (value) {
          this.setState({ inputText: value });
        }
        this.close();
      }
    } else if (key === 'Escape') {
      this.ignoreBlur = false;
      this.close();
    } else if (key === 'ArrowUp') {
      if (!isOpen || highlightedIndex === undefined) {
        return;
      }
      event.preventDefault();
      if (highlightedIndex === 0) {
        this.setState({ highlightedIndex: this.props.items.length - 1 });
      } else {
        this.setState({ highlightedIndex: highlightedIndex - 1 });
      }
    } else if (key === 'ArrowDown') {
      if (!isOpen || highlightedIndex === undefined) {
        this.setState({ highlightedIndex: 0 });
        this.maybeOpen();
        return;
      }
      event.preventDefault();
      if (highlightedIndex === this.props.items.length - 1) {
        this.setState({ highlightedIndex: 0 });
      } else {
        this.setState({ highlightedIndex: highlightedIndex + 1 });
      }
    }
  };

  selectHighlightedItem = () => {
    const { highlightedIndex } = this.state;
    if (highlightedIndex !== undefined) {
      const item = this.getItemByIndex(highlightedIndex);
      this.handleSelect(item);
    }
  };

  highlightItemFromMouse = (index: number) => {
    this.setState({ highlightedIndex: index });
  };

  selectItemFromMouse = (index: number) => {
    this.ignoreBlur = false;
    const item = this.getItemByIndex(index);
    this.handleSelect(item);
  };

  getItemByIndex = (index: number) => {
    return this.props.items[index];
  };

  componentDidUpdate(prevProps: Props, prevState: State) {
    const { itemsKey } = this.state;
    const { items } = this.props;

    if (items !== prevProps.items) {
      this.setState(state => ({ itemsKey: state.inputText }));
    }

    if (itemsKey !== prevState.itemsKey) {
      this.maybeOpen();
    }
  }

  render = () => {
    const { inputText, isFocused, isOpen, highlightedIndex } = this.state;
    const { placeholder, autoFocus, items } = this.props;

    const isVisible = isOpen && items.length > 0;

    return (
      <div
        onMouseEnter={() => {
          this.ignoreBlur = true;
        }}
        onMouseLeave={() => {
          this.ignoreBlur = false;
        }}
      >
        <Styled.SuggestionBar isFocused={isFocused}>
          <Styled.TextInput
            ref={this.inputRef}
            value={inputText}
            placeholder={placeholder}
            autoFocus={autoFocus}
            spellCheck={false}
            autoComplete="off"
            onChange={this.handleChange}
            onFocus={this.handleFocus}
            onBlur={this.handleBlur}
            onKeyDown={this.handleKeyDown}
          />
        </Styled.SuggestionBar>
        <SuggestionBox
          suggestions={items}
          isVisible={isVisible}
          highlightedIndex={highlightedIndex}
        />
      </div>
    );
  };
}

export default Autosuggest;

// src/components/search/Autosuggest.vue
<template>
    <div class="autosuggest" @mouseenter="ignoreBlur = true" @mouseleave="ignoreBlur = false">
        <div :class="{ '-focus': isFocused }" class="autosuggest-bar">
            <input
                ref="input"
                v-model="inputText"
                :placeholder="placeholder"
                :autofocus="autofocus"
                spellcheck="false"
                autocomplete="off"
                @input="handleInput"
                @focus="handleFocus"
                @blur="handleBlur"
                @keydown.enter="handleKeydownEnter($event)"
                @keydown.tab="handleKeydownTab"
                @keydown.escape="handleKeydownEscape"
                @keydown.up="handleKeydownUp($event)"
                @keydown.down="handleKeydownDown($event)"
            />
            <slot name="button-right"></slot>
        </div>
        <SuggestionBox :suggestions="items" :is-visible="isVisible">
            <template v-slot:item="{ suggestion, index }">
                <div
                    :class="{ '-highlight': highlightedIndex === index }"
                    class="suggestion"
                    @click="selectItemFromMouse(index)"
                    @mouseenter="highlightItemFromMouse(index)"
                    v-html="suggestion.highlight || suggestion.package.name"
                />
            </template>
        </SuggestionBox>
    </div>
</template>

<script lang="ts">
import Vue, { PropType } from 'vue';

import SuggestionBox from './SuggestionBox.vue';
import { Suggestion } from '@/types';

interface Data {
    inputText: string;
    isOpen: boolean;
    isFocused: boolean;
    highlightedIndex: number | null;
    ignoreBlur: boolean;
}

export default Vue.extend({
    components: {
        SuggestionBox,
    },
    props: {
        initialValue: {
            type: String,
            default: undefined,
        },
        placeholder: {
            type: String,
            default: undefined,
        },
        onSelect: {
            type: Function,
            required: true,
        },
        onInput: {
            type: Function,
            required: true,
        },
        items: {
            type: Array as PropType<Suggestion[]>,
            required: true,
        },
        itemsKey: {
            type: String,
            required: true,
        },
        getValueFromItem: {
            type: Function,
            required: true,
        },
        canBeOpened: {
            type: Function,
            required: true,
        },
        autofocus: {
            type: Boolean,
            default: false,
        },
    },
    data(): Data {
        return {
            inputText: '',
            isOpen: false,
            isFocused: false,
            highlightedIndex: null,
            ignoreBlur: false,
        };
    },
    computed: {
        isVisible(): boolean {
            return this.isOpen && this.items.length > 0;
        },
    },
    watch: {
        itemsKey() {
            // Every time items key changes, trigger the opening event.
            // This forces the parent to re-evaluate if suggestions can be visible
            // without "controlled" isOpen prop.
            // Another solution would be to emit events from child to parent,
            // but this is considered an anti-pattern.
            this.maybeOpen();
        },
    },
    created() {
        if (this.initialValue) {
            this.inputText = this.initialValue;
        }
    },
    methods: {
        maybeOpen() {
            if (this.isOpen) {
                return;
            }
            this.isOpen = this.isFocused && this.canBeOpened(this.inputText);
        },

        close() {
            this.isOpen = false;
            this.highlightedIndex = null;
        },

        handleSelect(item: Suggestion) {
            const value = this.getValueFromItem(item);
            this.onSelect(value);
            this.close();
            this.inputText = value;
        },

        handleInput() {
            this.onInput(this.inputText);
            this.maybeOpen();
            if (!this.inputText) {
                this.close();
            }
        },

        handleFocus() {
            this.isFocused = true;
            this.maybeOpen();
        },

        handleBlur() {
            if (this.ignoreBlur) {
                (this.$refs.input as HTMLInputElement).focus();
                return;
            }
            this.isFocused = false;
            this.close();
        },

        handleKeydownEnter(event: KeyboardEvent) {
            this.ignoreBlur = false;
            if (!this.isOpen) {
                return;
            } else if (this.highlightedIndex === null) {
                this.isOpen = false;
            } else {
                event.preventDefault();
                this.selectHighlightedItem();
            }
        },

        handleKeydownTab() {
            this.ignoreBlur = false;
            if (this.highlightedIndex !== null) {
                const item = this.getItemByIndex(this.highlightedIndex);
                const value = this.getValueFromItem(item);
                if (value) {
                    this.inputText = value;
                }
                this.close();
            }
        },

        handleKeydownEscape() {
            this.ignoreBlur = false;
            this.close();
        },

        handleKeydownUp(event: KeyboardEvent) {
            if (!this.isOpen || this.highlightedIndex === null) {
                return;
            }
            event.preventDefault();
            if (this.highlightedIndex === 0) {
                this.highlightedIndex = this.items.length - 1;
            } else {
                this.highlightedIndex--;
            }
        },

        handleKeydownDown(event: KeyboardEvent) {
            if (!this.isOpen || this.highlightedIndex === null) {
                this.highlightedIndex = 0;
                this.maybeOpen();
                return;
            }
            event.preventDefault();
            if (this.highlightedIndex === this.items.length - 1) {
                this.highlightedIndex = 0;
            } else {
                this.highlightedIndex++;
            }
        },

        selectHighlightedItem() {
            if (this.highlightedIndex !== null) {
                const item = this.getItemByIndex(this.highlightedIndex);
                this.handleSelect(item);
            }
        },

        highlightItemFromMouse(index: number) {
            this.highlightedIndex = index;
        },

        selectItemFromMouse(index: number) {
            this.ignoreBlur = false;
            const item = this.getItemByIndex(index);
            this.handleSelect(item);
        },

        getItemByIndex(index: number) {
            return this.items[index];
        },
    },
});
</script>

<style lang="scss" scoped>
@import 'helpers';

.autosuggest-bar {
    display: inline-flex;
    align-items: center;
    width: 100%;
    padding-right: 0.4em;
    padding-left: 0.8em;
    border-radius: 4px;
    border: 1px solid #ccc;

    &.-focus {
        border-color: #377acc;
        box-shadow: 0 0 0 1px #377acc;
    }

    input {
        border: 0;
        line-height: 2.2em;
        background: transparent;
        flex: 1;
        outline: 0;
        caret-color: #377acc;
    }
}

/deep/ .suggestion-box {
    margin-top: 8px;
    position: absolute;
    left: 0;
    right: 0;
}

/deep/ .suggestion {
    @extend %button-unstyled;

    flex: 1;
    padding: 0.4em 0.8em;
    cursor: pointer;

    &.-highlight {
        background: #eee;
    }

    /deep/ em {
        font-style: normal;
        font-weight: bold;
    }
}
</style>
